version: '3'

services:
  localstack:
    image: localstack/localstack:0.12.20
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack:/tmp/localstack/

volumes:
  localstack:
