version: '3'

services:
  localstack:
    image: localstack/localstack:0.12.20
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack:/tmp/localstack/

  localstack-full:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - localstack-full:/tmp/localstack/

volumes:
  localstack:
  localstack-full:
